
catalog:
  mysql:
    create: false
    endpoint: ${CATALOG_ENDPOINT}
    secret:
      create: true
      username: adminuser
      password: SuperSecretPass123!
      name: catalog-db

orders:
  postgresql:
    create: false
    endpoint:
      host: ${ORDERS_ENDPOINT}
      port: "5432"
    secret:
      create: true
      username: adminuser
      password: SuperSecretPass123!
      name: orders-db

ui:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
  service:
    type: ClusterIP
  endpoints:
    catalog: http://my-retail-app-catalog:80
    carts: http://my-retail-app-carts:80
    checkout: http://my-retail-app-checkout:80
    orders: http://my-retail-app-orders:80
    assets: http://my-retail-app-assets:80

checkout:
  endpoints:
    orders: http://my-retail-app-orders:80

carts:
  env:
    - name: AWS_REGION
      value: "us-east-1"
